import React, { useState } from 'react'

import SlideToggleContent from '../../ContentSlider/SlideToggleContent'
import ViewMoreTranscriptButton from '../ViewMoreTranscriptButton'

export default () => {
  const [isVisible, setIsVisible] = useState(false)
  return (
    <div className='col-xs-13'>
      <div className='row'>
        <div className='col-xs-2' />
        <div
          className='col-xs-8' style={{
            padding: '2rem 0'
          }}
        >
          <h2 style={{
            textAlign: 'center'
          }}
          >
        The Packet - Security Bytes - Ep.2: Privacy Primer
          </h2>
          <div dangerouslySetInnerHTML={{ __html: '<iframe title="The Packet - Security Bytes - Ep 2: Privacy Primer" style="border: none;" scrolling="no" data-name="pb-iframe-player" src="https://www.podbean.com/media/player/bkntq-ded1d4?from=yiiadmin&download=1&version=1&skin=11&btn-skin=101&auto=0&share=1&fonts=Helvetica&download=1&rtl=0&pbad=1" width="100%" height="122"></iframe>' }} />
          <div style={{
            paddingTop: '1rem'
            // textAlign: 'center'
          }}
          >
            <SlideToggleContent isVisible={isVisible}>
              <h3 className='transcript__h3'>Outline</h3>
              <li className='transcript__li'>Welcome to Security Bytes: Providing you with trusted insights and practical advice on how to navigate our hyper‐connected modern world.</li>
              <li className='transcript__li'>In this episode of Security Bytes, we're going to examine online privacy and provide a perspective on this important, but sometimes poorly understood, concept. To clear up the confusion around privacy, we will explore a model for thinking about personal information and establish informed choice as the core precept of privacy when sharing our personal information online.</li>
              <li className='transcript__li'>Once we have a better understanding of privacy, we will then come to the unfortunate conclusion that we, the general public, have lost control over our online personal information, and hence our privacy. To round out the episode, we will give you some advice on how you can regain and protect your privacy while still enjoying the benefits of being online; taking actions to limit the tracking of your information, and methods on how to muddy your online presence.</li>
              <li className='transcript__li'>We will also introduce a tool that the Institute has created to help you do it.</li>
              <h3 className='transcript__h3'>What is privacy?</h3>
              <li className='transcript__li'>Online privacy discussions tend to start and focus on technical issues and details, firewalls, antivirus, etc. While technology has a significant role to play in the protection, and to be frank exploitation, of our online privacy, it is not the keystone concept.</li>
              <li className='transcript__li'>At its heart, privacy is about each individual person, their personal information, and their agency over it.</li>

              <li className='transcript__li'>Think of personal information as coming in two forms, information that is about you and information that is you.</li>
              <li className='transcript__li'>Information that is about you, are tangible details of yourself or things you possess, like: date of birth; credit card number; home address; phone number; and, email addresses.</li>
              <li className='transcript__li'>Information about you is important online because it is used to prove who you are; which of course makes it a prime target for those engaged in identity theft. Information about you in the online context, is information you explicitly provide. Say, when you sign up for a social media account or purchase something through an eCommerce site.</li>
              <li className='transcript__li'>As about you information must be explicitly provided, you can consciously change or fabricate it, allowing for a degree of pseudonymity, but more on that later.</li>
              <li className='transcript__li'>A finally important consideration with about you information, is that it is used to link and glue together disparate blobs of personal information –about you and is you –information into a coherent whole.</li>
              <li className='transcript__li'>Is you information is much harder to mask or fabricate, as it is not directly supplied by you, but generated through observing you, your behaviours, and your preferences.</li>
              <li className='transcript__li'>This information forms your digital DNA and it can be used to identify, analyse, influence, and unfortunately manipulate you. Is you information, your digital DNA, is information related to your behaviours, actions and preferences. These subconscious expressions of yourself include things such as: what music you like; what your political views are; people or businesses you interact with; your purchasing habits; where and how you travel; and in general, how you react in different situations.</li>           
              <li className='transcript__li'>And we express these habits, behaviours, and preferences all the time without even thinking about them. Your digital DNA can be exploited by the unscrupulous to psychologically influence us, manipulating us to act with an incomplete or incorrect perspective.</li>
              <li className='transcript__li'>Some simple, but all too common examples of this are:
                <ul type='circle'>
                  <li>Hyper‐targeted social media advertising to encourage and exploit impulse buying informed by our search history, social media posts, and even things we've mentioned in chat apps or to digital assistance; and,</li>
                  <li>There is also the algorithmic curation of our personal social media feeds showing us content that makes us want to consume more content. More content served equals more advertising revenue for the platform provider. This shaping of our media consumption narrows our exposure to different opinions and reinforces our specific world view, whether it reflects reality or not.</li>
                </ul>
              </li>
              <li className='transcript__li'>The darkpatterns.org website provides some good examples of these practices, and their more nefarious siblings.</li>
              <li className='transcript__li'>In summary, information is about you or is you. Information about you are superficial facts and identifiers that can be consciously changed, and that malicious actors seek in order to steal your identity. Whereas information that is you is intrinsically tied to your subconscious behaviours and therefore difficult to mask. This digital DNA is sought by legitimate and malicious actors in order to influence your actions.</li>
              <h3 className='transcript__h3'>So how does this relate to privacy?</h3>
              <li className='transcript__li'>Privacy equals choice. We view privacy as an individual’s right and capacity to make informed decisions over how much, to whom, and on what terms they share or withhold their personal information. Further, anyone collecting personal information must respect an individual's choices.</li>
              <li className='transcript__li'>It is informed choice that sits at the heart of privacy, not as may spring to mind, an image of personal information being hidden and kept secret under all circumstances. By focusing on informed choice we move the conversation away from getting bogged down, talking about technology or paranoid stereotypes.</li>
              <li className='transcript__li'>Capturing an individual's prerogative of privacy that includes everything from those wanting to withhold all personal information online, to those living their life out loud on social media. In both these scenarios, it is not the eventual actions that occur to the individual's personal data that is important. But that the individual chose to have their personal information collected, use protected, and shared in that manner, in the full knowledge of how it would be done and the collector being upfront about the consequences of that choice.</li>
              <li className='transcript__li'>And there's the rub.</li>
              <h3 className='transcript__h3'>We have lost informed choice and lost agency over our data.</h3>
              <li className='transcript__li'>It is now impossible for the average person to comprehend the scale on which their personal information is collected and on what terms it is being used and traded. With which, there can be no informed choice, which in turn implies a loss of agency and control over personal information online.</li>
              <li className='transcript__li'>To illustrate this, consider the hyper‐connected modern world and all the online actions that have been logged. A tiny set of these are: what sites and services you visit; when you visited them; how long you dwelled there; where your mouse hovered; what you bought; what page you browse from; what advertising you clicked; and, from which unique device you were browsing from.</li>
              <li className='transcript__li'>Through mechanisms such as tracking cookies in browsers, each interaction can be recorded many times, by many different brokers.</li>
              <li className='transcript__li'>But it is not just our conscious actions on the internet that are recorded. Most of us carry a mobile device, which contains an extremely powerful sensor of platform ‐ when allowed to ‐ it collects and forwards an enormous array of information. Information that is you: where you have been; what routes you took; who you have been near and for how long; how fast you travelled; and, how healthy you are, if paired with your activity tracker or smartwatch.</li>
              <li className='transcript__li'>If allowed to, it essentially tracks you in physical space the same way you are tracked online.</li>
              <li className='transcript__li'>This occurs when we load apps and blithely agree to permissions when installing them and astounding number of apps ask for access to the full array of sensors to record and forward all manner of movement, location, and environmental information.</li>
              <li className='transcript__li'>And, of course, there is also the mundane; who we contacted and when.</li>
              <li className='transcript__li'>Mobiles, and similar devices, with inbuilt digital assistants listen for a trigger word to wake up. They must therefore be listening all the time to catch these. There have been instances where companies collecting this audio data have breached privacy through using the audio for unexpected, and sometimes voyeuristic, purposes.</li>
              <li className='transcript__li'>Even though we are not paying money to Facebook, Instagram, Twitter, or Gmail, they are generating revenue from our personal information; the classic being through advertising. As the old saying goes, if you're not paying for the product, you are the product. Given the scale of collection, processing, storage, and the thriving data sharing trade between companies, data‐centric companies are increasingly able to recover and exploit more and more of your digital DNA.</li>
              <li className='transcript__li'>While most of us may be tolerant towards the hyper targeting of advertising, or satisfied to be served with content we are more interested in, you need to consider that it is the same mechanisms and personal information that enable the undue influencing of elections and destabilization of nation‐states through the spread of targeted fake news.</li>
              <h3 className='transcript__h3'>So why is this allowed to happen?</h3>
              <li className='transcript__li'>To borrow from Bruce Schneier, talking on privacy “those entrusted with our privacy don't have much incentive to respect it.” In most jurisdictions, the penalty for lack of compliance or breach of privacy laws is relatively low. For the large data collectors and brokers, the penalties are trivial when compared to the revenue they generate from their activities. Large data brokers are able to weather the bad press, pay the small fine and quickly continue to operate.</li>
              <li className='transcript__li'>When large data‐centric multinationals encounter a legislative obstacle, they can quickly move troublesome information collection functions into more permissive jurisdictions; a similar idea to minimizing taxation through routing online payments through different countries.</li>
              <li className='transcript__li'>But more worrying than these dubious business models built around collecting and selling personal information, is that we unwittingly but willingly, sign away our privacy rights all the time when we sign up to online services through accepting the Terms and Conditions.</li>
              <li className='transcript__li'>These Terms and Conditions are typically an impenetrable mass of legalese, covering the service provided and what the user provides in exchange. Most of us simply click through them without reading, keen to get onto the new social media platform or play crazy cupcakes as soon as we can.</li>
              <li className='transcript__li'>Terms and Conditions are long, dense and full of very, very boring, but very, very important text.</li>
              <li className='transcript__li'>As shown by this example on April 1st, 2010 a UK‐based eCommerce company called Gamestation decided to highlight this inattention to Terms and Conditions by altering theirs to include this clause:</li>
              <li className='transcript__li'>"By placing an order via this website on the first day of the fourth month of the year 2010 Anno Domini you agree to grant us a non‐transferable option to claim for now and forevermore, your immortal soul. Should we wish to exercise this option, you agree to surrender your immortal soul and any claim you may have on it, within five working days of receiving written notification from Gamestation or one of its duly authorized minions."</li>
              <li className='transcript__li'>And just like that, albeit as a joke, over the day Gamestation gained an option to harvest seven and a half thousand souls. Only about one in 10 shoppers noticed and opted out of that particular clause and won a store voucher for their attention.</li>
              <li className='transcript__li'>While this is a legendary April Fool's Day prank, it shows how inattentive we are with Terms and Conditions, seemingly taking it as an article of faith that nothing bad will happen. But buried in many dubious Terms and Conditions is language covering the use of data for the company's own hands, or sharing collected data with third parties for vague purposes.</li>
              <li className='transcript__li'>It is these clauses, when agreed to, that allow a business or entity to collect, use and sell your personal data with a somewhat effective legal shield.</li>
              <li className='transcript__li'>As we can now see, and Schneider pointed out to us before, there is no impetus for large data brokers to take privacy seriously. They still keep making money, and we still keep signing up.</li>
              <li className='transcript__li'>The data brokering market is convoluted, obfuscated behind legalese, and notoriously secretive about their operations and partnerships. I know; the terrible irony.</li>
              <li className='transcript__li'>At this time in the evolution of cyber there cannot be informed choice. Bluntly, for a data‐centric company to encourage informed choice and take privacy seriously, would cost advertising revenue. In the absence of a strong legal or commercial penalty, there is no strong business imperative for privacy to be taken seriously.</li>
              <li className='transcript__li'>For many of us, we may be willing to pay a high price in terms of personal data for a service, and that is each individual's prerogative. But as things stand, none of us can be certain of what we have signed away, or confident that our wishes will be respected by large data companies. We are not implying that large data brokers are intentionally malicious but consider: who do you think wins out in the battle between your privacy, for which we have seen there is no incentive to respect or protect, and shareholder value?</li>
              <li className='transcript__li'>So given the outlook is grim what are our options? First, the usual online security things: block third party and persistent cookies ‐ do a web search to find out how for your browser; say ‘N for numbat’ no, whenever asked if you want to personalise search results or user experience by an online app, search engine, or operating system. The only way to manage that personalisation is to collect and determine your online DNA.</li>
              <li className='transcript__li'>Don't give phone applications permissions to access sensors or data on your phone unless absolutely required for the type of service they are providing you. Be very cynical here.</li>
              <li className='transcript__li'>On the about you information front, limit the personal information you give out to social media and online services. In Australia, where the Cyber Institute is based, the Australian Privacy Principles give you the right of anonymity and pseudonymity. That is, you have the right to decline, or give made‐up information, to an online service. There are common sense exceptions to this, for example, where you cannot provide false information to law enforcement or to the tax office. When dealing with the government or financial institutions, etc., you must provide true details.</li>
              <li className='transcript__li'>But, just because of social media site or a phone app asks for personal information, doesn't mean you have to give it to them. You are well within your rights to consider each request for personal information and determine if it is in your interests to share it.</li>
              <li className='transcript__li'>Now onto is you information. We’ve already mentioned that it is hard to mask or fake ‐ so is all lost in this front? Not entirely.</li>
              <li className='transcript__li'>While we cannot fake or mask is you information, we can blur it. In the same way in which real life DNA tests can be corrupted by the presence of other biological material, so to can your digital DNA. A way of contaminating, or blurring, your digital DNA is to maintain a suite of different online personas, each with a different pseudonym, details and burner email address.</li>
              <li className='transcript__li'>This can then be used to segment your different interactions online, making it harder for your whole set of personal information to be aggregated and exploited. That is, something like; have a persona for your social media,have a different persona for your online shopping, your school, etc. You can then provide correct details only to those entities that require it by law, or where it is absolutely necessary.</li>
              <li className='transcript__li'>Each of these personas can then have a risk profile that you can manage easier, allowing you to make your personal choices for each of, say, social media, e‐commerce, or however else you decide to segment your online presence. For example, your social media profile may have completely false information, whereas your eCommerce persona may have your proper name and credit card details only.</li>
              <li className='transcript__li'>If this sounds all a bit too daunting to manage, the Institute has just created a new tool for the Chrome browser called SafeLy. SafeLy allows you to create, delete, and manage online personas through a Chrome plugin. The plugin allows you to create temporary burner email addresses and personas, which you can provide to online services during sign‐up. It acts like a cut‐out, allowing you to receive verification links without having to provide your personal email address to the platform. Combining the use of SafeLy with a password manager like Lastpass, 1password or KeePass, and you now have a solid mechanism for creating multiple personas and having full agency over the information.</li>
              <li className='transcript__li'>The sobering fact is online privacy is not a given. With the complexity and volume of social media platforms, the impenetrable Terms and Conditions, legalese and business practices that range from sloppy to unscrupulous, to have any privacy each individual has to get informed and consciously actto regain control. In the absence of deliberate effort from all of us, such as installing cookie blockers, SafeLy, etc, large data brokers will continue to use our personal information to their advantage in any manner they see fit.</li>
              <li className='transcript__li'>The only option is to get out there, get informed, retake your privacy, and make your conscious personal choices.</li>
              <li className='transcript__li'>A transcript for this episode is on the Cyber Institute website. It's cyber.anu.edu.au/news. From all of us here at the Cyber Institute, thanks for joining us. Until next time, stay safe and stay informed.</li>
            </SlideToggleContent>
            <div className='col-xs-12 center-xs'>
              <ViewMoreTranscriptButton isVisible={isVisible} clickButton={() => setIsVisible(!isVisible)} />
            </div>
          </div>
        </div>
        <div className='col-xs-2' />
      </div>
    </div>
  )
}
